FROM golang:1.7.3-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git

WORKDIR "$GOPATH/src/github.com/anthonynsimon/parrot/parrot-api"

COPY . .

RUN chmod +rwx ./start.sh

EXPOSE 443

CMD ["/bin/bash", "./start.sh"]